spring.application.name=surotec-academy

# ===================================================================
# =                   CONFIGURACION DE DATOS                        =
# ===================================================================

# Acceso a la base de datos usando variables de entorno de Render
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# ===================================================================
# =                  CONFIGURACION DE JPA/HIBERNATE                 =
# ===================================================================

# Dialecto optimizado para MySQL 8 (el que usa SmarterASP)
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# Cambiamos a 'validate' para proteger tus datos existentes
spring.jpa.hibernate.ddl-auto=validate

spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# ===================================================================
# =                         ESTABILIDAD HIKARI                      =
# ===================================================================
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-test-query=SELECT 1

# ===================================================================
# =                             SWAGGER                             =
# ===================================================================
springdoc.swagger-ui.path=/documentacion-api
springdoc.swagger-ui.enabled=true

# Puerto dinamico para Render
server.port=${PORT:8086}